version: '3.4'

services:
  api:
    environment:
      - WAIT_BEFORE_HOSTS=5
      - WAIT_HOSTS=db:1433
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "56042:80"

  db:
    environment:
      MSSQL_SA_PASSWORD: "Pa55w0rd2019"
      ACCEPT_EULA: "Y"
    ports: 
      - "1446:1433" 

  redis:
    ports:
     - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  tests:
    environment:
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS: api:80
      API_URL: http://api