version: '3.4'

services:
  api:
    environment:
      - WAIT_BEFORE_HOSTS=5
      - WAIT_HOSTS=db:1433
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5150:80"

  db:
    environment:
      MSSQL_SA_PASSWORD: "Pa55w0rd2019"
      ACCEPT_EULA: "Y"
    ports: 
      - "1446:1433" 
      
  seq:
    environment:
      ACCEPT_EULA: "Y"
    ports:
     - "5341:80"

  redis:
    ports:
     - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          memory: 20M
      restart_policy:
        condition: on-failure
        max_attempts: 3

  tests:
    environment:
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS: api:80
      API_URL: http://api