version: '3.4'

services:
  speakermeet.api:
    image: ${DOCKER_REGISTRY-}speakermeetapi
    build:
      context: .
      dockerfile: src/SpeakerMeet.Api/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        MSSQL_SA_PASSWORD: "Pa55w0rd2019"
        ACCEPT_EULA: "Y"
    ports: 
      - "1446:1433" 
