version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}speakermeetapi
    build:
      context: .
      dockerfile: src/SpeakerMeet.Api/Dockerfile
    depends_on:
      - db
      - redis
  
  db:
    image: "mcr.microsoft.com/mssql/server"
  
  redis:
    image: redis:alpine
  
  tests:
    build:
      context: .
      dockerfile: tests/SpeakerMeet.Tests.Integration.DB/Dockerfile
      target: build
    volumes: 
      - ./tests/SpeakerMeet.Tests.Integration.DB:/tests/SpeakerMeet.Tests.Integration.DB
    depends_on:
      - db
      - redis
      - api      