apiVersion: apps/v1
kind: Deployment
metadata:
  name: speakermeet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speakermeet-api
  template:
    metadata:
      labels:
        app: speakermeet-api
        version: image_label
    spec:
      containers:
      - name: speakermeet-api
        image: acr_url/speakermeet-api:image_label
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: ConnectionStrings__SpeakerMeet
          value: Server=db;Database=SpeakerMeet;User=sa;Password=P@55w0rd2019
        - name: Cache__Configuration
          value: redis:6379
        - name: Cache__Instancename
          value: redis
        - name: WAIT_HOSTS
          value: 'db:1433'
        - name: WAIT_HOSTS_TIMEOUT
          value: '30'
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: speakermeet-api
spec:
  type: NodePort
  selector:
    app: speakermeet-api
  ports:
  - port: 80
    targetPort: 80
