name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore SpeakerMeet.Api.sln
    - name: Build
      run: dotnet build SpeakerMeet.Api.sln --configuration Release --no-restore 
    - name: Test
      run: dotnet test SpeakerMeet.Api.sln --filter "FullyQualifiedName!~SpeakerMeet.Tests.Integration.DB" --no-restore --verbosity normal /p:Exclude="[Tests*].*" --collect:"XPlat Code Coverage"
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)